// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "gettext.h"
#include "kctsdialog.h"
#include <FL/Fl_Text_Buffer.H>

static void cb_mnuOpen(Fl_Menu_*, void*) {
  openFile();
}

static void cb_mnuSave(Fl_Menu_*, void*) {
  saveFile();
}

static void cb_mnuSaveAs(Fl_Menu_*, void*) {
  saveFileAs();
}

static void cb_mnuExit(Fl_Menu_*, void*) {
  exit(0);
}

static void cb_mnuEvents(Fl_Menu_*, void*) {
  debug::show();
}

static void cb_mnuOnLineHelp(Fl_Menu_*, void*) {
  visit_URL((void *)("http://www.w1hkj.com/kcts-help/index.html"));
}

static void cb_mnuAbout(Fl_Menu_*, void*) {
  about();
}

Fl_Menu_Item menu_[] = {
 {_("&Files"), 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&Open"), 0,  (Fl_Callback*)cb_mnuOpen, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&Save"), 0,  (Fl_Callback*)cb_mnuSave, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {_("Save &As"), 0,  (Fl_Callback*)cb_mnuSaveAs, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {_("E&xit"), 0,  (Fl_Callback*)cb_mnuExit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {_("&Events"), 0,  (Fl_Callback*)cb_mnuEvents, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&Help"), 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {_("On-line help"), 0,  (Fl_Callback*)cb_mnuOnLineHelp, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&About"), 0,  (Fl_Callback*)cb_mnuAbout, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Output *txtFirmware=(Fl_Output *)0;

Fl_Output *txtHardware=(Fl_Output *)0;

Fl_Input *txtSerialNumber=(Fl_Input *)0;

Fl_Button *btnSendSerialNbr=(Fl_Button *)0;

static void cb_btnSendSerialNbr(Fl_Button*, void*) {
  sendSerialNumber();
}

Fl_Output *txtRxSigLevel=(Fl_Output *)0;

Fl_Output *txtTemperature=(Fl_Output *)0;

Fl_Output *txtFwdPower=(Fl_Output *)0;

Fl_Output *txtRefPower=(Fl_Output *)0;

Fl_Button *btnReadAll=(Fl_Button *)0;

static void cb_btnReadAll(Fl_Button*, void*) {
  readAll();
}

Fl_Input *sMeter[16]={(Fl_Input *)0};

Fl_Button *btnReadSmeter=(Fl_Button *)0;

static void cb_btnReadSmeter(Fl_Button*, void*) {
  readSMeterData();
}

Fl_Button *btnSetSmeterData=(Fl_Button *)0;

static void cb_btnSetSmeterData(Fl_Button*, void*) {
  sendSMeterData();
}

Fl_Button *btnPerformSMeterCalibration=(Fl_Button *)0;

static void cb_btnPerformSMeterCalibration(Fl_Button*, void*) {
  performSMeterCalibration();
}

XYplot *pltSMeter=(XYplot *)0;

Fl_Input *freqRef[32]={(Fl_Input *)0};

Fl_Button *btnReadFreqRefData=(Fl_Button *)0;

static void cb_btnReadFreqRefData(Fl_Button*, void*) {
  readFreqRefData();
}

Fl_Button *btnSetFreqRefData=(Fl_Button *)0;

static void cb_btnSetFreqRefData(Fl_Button*, void*) {
  sendFreqRefData();
}

XYplot *pltFreqRef=(XYplot *)0;

Fl_Button *btnFreqRefCalibrate=(Fl_Button *)0;

static void cb_btnFreqRefCalibrate(Fl_Button*, void*) {
  performFreqRefCalibration();
}

Fl_Input *phase[16]={(Fl_Input *)0};

XYplot *pltPhase=(XYplot *)0;

Fl_Button *btnReadPhaseData=(Fl_Button *)0;

static void cb_btnReadPhaseData(Fl_Button*, void*) {
  readPhaseData();
}

Fl_Button *btnSetPhaseData=(Fl_Button *)0;

static void cb_btnSetPhaseData(Fl_Button*, void*) {
  sendPhaseData();
}

Fl_Button *btnPhaseCalibrate=(Fl_Button *)0;

static void cb_btnPhaseCalibrate(Fl_Button*, void*) {
  performPhaseCalibration();
}

Fl_Button *btnReadCarrierData=(Fl_Button *)0;

static void cb_btnReadCarrierData(Fl_Button*, void*) {
  readCarrierData();
}

Fl_Button *btnSetCarrierData=(Fl_Button *)0;

static void cb_btnSetCarrierData(Fl_Button*, void*) {
  sendCarrierData();
}

Fl_Input *valCarrierBalance=(Fl_Input *)0;

Fl_Button *btnCarrierBalance=(Fl_Button *)0;

static void cb_btnCarrierBalance(Fl_Button*, void*) {
  performCarrierBalance();
}

Fl_Output *txtAGC=(Fl_Output *)0;

Fl_Output *txtLockDet1=(Fl_Output *)0;

Fl_Output *txtLockDet2=(Fl_Output *)0;

Fl_Output *txtFwdPwr=(Fl_Output *)0;

Fl_Output *txtRefPwr=(Fl_Output *)0;

Fl_Output *txtPhaseDet=(Fl_Output *)0;

Fl_Output *txtTxAudio=(Fl_Output *)0;

Fl_Output *txtTempA=(Fl_Output *)0;

Fl_Output *txtTempB=(Fl_Output *)0;

Fl_Output *txtTCXO=(Fl_Output *)0;

Fl_Button *btnReadAGC=(Fl_Button *)0;

static void cb_btnReadAGC(Fl_Button*, void*) {
  readAGC();
}

Fl_Button *btnReadLockDet1=(Fl_Button *)0;

static void cb_btnReadLockDet1(Fl_Button*, void*) {
  readLockDet1();
}

Fl_Button *btnReadLockDet2=(Fl_Button *)0;

static void cb_btnReadLockDet2(Fl_Button*, void*) {
  readLockDet2();
}

Fl_Button *btnReadFwdPwr=(Fl_Button *)0;

static void cb_btnReadFwdPwr(Fl_Button*, void*) {
  readFwdPwr();
}

Fl_Button *btnReadRefPwr=(Fl_Button *)0;

static void cb_btnReadRefPwr(Fl_Button*, void*) {
  readRefPwr();
}

Fl_Button *btnPhaseDet=(Fl_Button *)0;

static void cb_btnPhaseDet(Fl_Button*, void*) {
  readPhaseDet();
}

Fl_Button *btnTxAudio=(Fl_Button *)0;

static void cb_btnTxAudio(Fl_Button*, void*) {
  readTxAudio();
}

Fl_Button *btnReadTempA=(Fl_Button *)0;

static void cb_btnReadTempA(Fl_Button*, void*) {
  readTempA();
}

Fl_Button *btnReadTempB=(Fl_Button *)0;

static void cb_btnReadTempB(Fl_Button*, void*) {
  readTempB();
}

Fl_Button *btnReadTCXO=(Fl_Button *)0;

static void cb_btnReadTCXO(Fl_Button*, void*) {
  readTCXO();
}

Fl_Double_Window* make_TSdialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(500, 300, _("Kachina Test Suite"));
    w = o;
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 500, 20);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Tabs* o = new Fl_Tabs(0, 22, 500, 295);
      { Fl_Group* o = new Fl_Group(0, 45, 500, 255, _("Gen"));
        { Fl_Group* o = new Fl_Group(10, 55, 480, 67);
          o->box(FL_ENGRAVED_FRAME);
          { txtFirmware = new Fl_Output(90, 61, 54, 24, _("Firmware:"));
          } // Fl_Output* txtFirmware
          { txtHardware = new Fl_Output(235, 61, 54, 24, _("Hardware:"));
          } // Fl_Output* txtHardware
          { txtSerialNumber = new Fl_Input(370, 61, 107, 24, _("Serial #:"));
          } // Fl_Input* txtSerialNumber
          { btnSendSerialNbr = new Fl_Button(400, 89, 75, 25, _("Set Serial"));
            btnSendSerialNbr->tooltip(_("Write Serial # to NRAM (tbd)"));
            btnSendSerialNbr->callback((Fl_Callback*)cb_btnSendSerialNbr);
          } // Fl_Button* btnSendSerialNbr
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(10, 125, 190, 170);
          o->box(FL_ENGRAVED_FRAME);
          { txtRxSigLevel = new Fl_Output(120, 135, 63, 24, _("Rx Sig Level:"));
          } // Fl_Output* txtRxSigLevel
          { txtTemperature = new Fl_Output(120, 175, 63, 24, _("Temperature:"));
          } // Fl_Output* txtTemperature
          { txtFwdPower = new Fl_Output(120, 215, 63, 24, _("Fwd Pwr:"));
            txtFwdPower->hide();
          } // Fl_Output* txtFwdPower
          { txtRefPower = new Fl_Output(120, 256, 63, 24, _("Ref Pwr:"));
            txtRefPower->hide();
          } // Fl_Output* txtRefPower
          o->end();
        } // Fl_Group* o
        { btnReadAll = new Fl_Button(400, 130, 75, 25, _("Read All"));
          btnReadAll->callback((Fl_Callback*)cb_btnReadAll);
        } // Fl_Button* btnReadAll
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 45, 500, 255, _("Smeter"));
        o->hide();
        { sMeter[0] = new Fl_Input(75, 55, 50, 24, _("+20 dbm:"));
          sMeter[0]->type(2);
        } // Fl_Input* sMeter[0]
        { sMeter[1] = new Fl_Input(75, 80, 50, 24, _("+10 dbm:"));
          sMeter[1]->type(2);
        } // Fl_Input* sMeter[1]
        { sMeter[2] = new Fl_Input(75, 106, 50, 24, _("0 dbm:"));
          sMeter[2]->type(2);
        } // Fl_Input* sMeter[2]
        { sMeter[3] = new Fl_Input(75, 132, 50, 24, _("-10 dbm:"));
          sMeter[3]->type(2);
        } // Fl_Input* sMeter[3]
        { sMeter[4] = new Fl_Input(75, 158, 50, 24, _("-20 dbm:"));
          sMeter[4]->type(2);
        } // Fl_Input* sMeter[4]
        { sMeter[5] = new Fl_Input(75, 184, 50, 24, _("-30 dbm:"));
          sMeter[5]->type(2);
        } // Fl_Input* sMeter[5]
        { sMeter[6] = new Fl_Input(75, 210, 50, 24, _("-40 dbm:"));
          sMeter[6]->type(2);
        } // Fl_Input* sMeter[6]
        { sMeter[7] = new Fl_Input(75, 236, 50, 24, _("-50 dbm:"));
          sMeter[7]->type(2);
        } // Fl_Input* sMeter[7]
        { sMeter[8] = new Fl_Input(204, 55, 50, 24, _("-60 dbm:"));
          sMeter[8]->type(2);
        } // Fl_Input* sMeter[8]
        { sMeter[9] = new Fl_Input(204, 80, 50, 24, _("-70 dbm:"));
          sMeter[9]->type(2);
        } // Fl_Input* sMeter[9]
        { sMeter[10] = new Fl_Input(204, 106, 50, 24, _("-80 dbm:"));
          sMeter[10]->type(2);
        } // Fl_Input* sMeter[10]
        { sMeter[11] = new Fl_Input(204, 132, 50, 24, _("-90 dbm:"));
          sMeter[11]->type(2);
        } // Fl_Input* sMeter[11]
        { sMeter[12] = new Fl_Input(204, 158, 50, 24, _("-100 dbm:"));
          sMeter[12]->type(2);
        } // Fl_Input* sMeter[12]
        { sMeter[13] = new Fl_Input(204, 184, 50, 24, _("-110 dbm:"));
          sMeter[13]->type(2);
        } // Fl_Input* sMeter[13]
        { sMeter[14] = new Fl_Input(204, 210, 50, 24, _("-120 dbm:"));
          sMeter[14]->type(2);
        } // Fl_Input* sMeter[14]
        { sMeter[15] = new Fl_Input(204, 236, 50, 24, _("-130 dbm:"));
          sMeter[15]->type(2);
        } // Fl_Input* sMeter[15]
        { btnReadSmeter = new Fl_Button(5, 266, 75, 24, _("Read"));
          btnReadSmeter->tooltip(_("Read NRAM values from rig."));
          btnReadSmeter->callback((Fl_Callback*)cb_btnReadSmeter);
        } // Fl_Button* btnReadSmeter
        { btnSetSmeterData = new Fl_Button(92, 266, 75, 24, _("Write"));
          btnSetSmeterData->tooltip(_("Write values to rig NRAM"));
          btnSetSmeterData->callback((Fl_Callback*)cb_btnSetSmeterData);
        } // Fl_Button* btnSetSmeterData
        { btnPerformSMeterCalibration = new Fl_Button(180, 266, 75, 24, _("Calibrate"));
          btnPerformSMeterCalibration->tooltip(_("Perform Smeter Calibration"));
          btnPerformSMeterCalibration->callback((Fl_Callback*)cb_btnPerformSMeterCalibration);
        } // Fl_Button* btnPerformSMeterCalibration
        { pltSMeter = new XYplot(260, 55, 230, 240);
          pltSMeter->box(FL_DOWN_BOX);
          pltSMeter->color((Fl_Color)FL_BACKGROUND2_COLOR);
          pltSMeter->selection_color((Fl_Color)FL_BACKGROUND2_COLOR);
          pltSMeter->labeltype(FL_NORMAL_LABEL);
          pltSMeter->labelfont(0);
          pltSMeter->labelsize(14);
          pltSMeter->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
          pltSMeter->align(FL_ALIGN_CENTER);
          pltSMeter->when(FL_WHEN_RELEASE);
        } // XYplot* pltSMeter
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 45, 500, 255, _("FreqRef"));
        o->hide();
        { freqRef[0] = new Fl_Input(10, 50, 48, 24);
        } // Fl_Input* freqRef[0]
        { freqRef[1] = new Fl_Input(60, 50, 48, 24);
        } // Fl_Input* freqRef[1]
        { freqRef[2] = new Fl_Input(111, 50, 48, 24);
        } // Fl_Input* freqRef[2]
        { freqRef[3] = new Fl_Input(162, 50, 48, 24);
        } // Fl_Input* freqRef[3]
        { freqRef[4] = new Fl_Input(212, 50, 48, 24);
        } // Fl_Input* freqRef[4]
        { freqRef[5] = new Fl_Input(263, 50, 48, 24);
        } // Fl_Input* freqRef[5]
        { freqRef[6] = new Fl_Input(314, 50, 48, 24);
        } // Fl_Input* freqRef[6]
        { freqRef[7] = new Fl_Input(365, 50, 48, 24);
        } // Fl_Input* freqRef[7]
        { freqRef[8] = new Fl_Input(10, 75, 48, 24);
        } // Fl_Input* freqRef[8]
        { freqRef[9] = new Fl_Input(60, 75, 48, 24);
        } // Fl_Input* freqRef[9]
        { freqRef[10] = new Fl_Input(111, 75, 48, 24);
        } // Fl_Input* freqRef[10]
        { freqRef[11] = new Fl_Input(162, 75, 48, 24);
        } // Fl_Input* freqRef[11]
        { freqRef[12] = new Fl_Input(212, 75, 48, 24);
        } // Fl_Input* freqRef[12]
        { freqRef[13] = new Fl_Input(263, 75, 48, 24);
        } // Fl_Input* freqRef[13]
        { freqRef[14] = new Fl_Input(314, 75, 48, 24);
        } // Fl_Input* freqRef[14]
        { freqRef[15] = new Fl_Input(365, 75, 48, 24);
        } // Fl_Input* freqRef[15]
        { freqRef[16] = new Fl_Input(10, 100, 48, 24);
        } // Fl_Input* freqRef[16]
        { freqRef[17] = new Fl_Input(60, 100, 48, 24);
        } // Fl_Input* freqRef[17]
        { freqRef[18] = new Fl_Input(111, 100, 48, 24);
        } // Fl_Input* freqRef[18]
        { freqRef[19] = new Fl_Input(162, 100, 48, 24);
        } // Fl_Input* freqRef[19]
        { freqRef[20] = new Fl_Input(212, 100, 48, 24);
        } // Fl_Input* freqRef[20]
        { freqRef[21] = new Fl_Input(263, 100, 48, 24);
        } // Fl_Input* freqRef[21]
        { freqRef[22] = new Fl_Input(314, 100, 48, 24);
        } // Fl_Input* freqRef[22]
        { freqRef[23] = new Fl_Input(365, 100, 48, 24);
        } // Fl_Input* freqRef[23]
        { freqRef[24] = new Fl_Input(10, 125, 48, 24);
        } // Fl_Input* freqRef[24]
        { freqRef[25] = new Fl_Input(60, 125, 48, 24);
        } // Fl_Input* freqRef[25]
        { freqRef[26] = new Fl_Input(111, 125, 48, 24);
        } // Fl_Input* freqRef[26]
        { freqRef[27] = new Fl_Input(162, 125, 48, 24);
        } // Fl_Input* freqRef[27]
        { freqRef[28] = new Fl_Input(212, 125, 48, 24);
        } // Fl_Input* freqRef[28]
        { freqRef[29] = new Fl_Input(263, 125, 48, 24);
        } // Fl_Input* freqRef[29]
        { freqRef[30] = new Fl_Input(314, 125, 48, 24);
        } // Fl_Input* freqRef[30]
        { freqRef[31] = new Fl_Input(365, 125, 48, 24);
        } // Fl_Input* freqRef[31]
        { btnReadFreqRefData = new Fl_Button(418, 50, 75, 24, _("Read"));
          btnReadFreqRefData->tooltip(_("Read NRAM values from rig."));
          btnReadFreqRefData->callback((Fl_Callback*)cb_btnReadFreqRefData);
        } // Fl_Button* btnReadFreqRefData
        { btnSetFreqRefData = new Fl_Button(418, 87, 75, 24, _("Write"));
          btnSetFreqRefData->tooltip(_("Write values to rig NRAM"));
          btnSetFreqRefData->callback((Fl_Callback*)cb_btnSetFreqRefData);
        } // Fl_Button* btnSetFreqRefData
        { pltFreqRef = new XYplot(10, 152, 480, 146, _("Plot Goes Here"));
          pltFreqRef->box(FL_DOWN_BOX);
          pltFreqRef->color((Fl_Color)FL_BACKGROUND2_COLOR);
          pltFreqRef->selection_color((Fl_Color)FL_BACKGROUND2_COLOR);
          pltFreqRef->labeltype(FL_NORMAL_LABEL);
          pltFreqRef->labelfont(0);
          pltFreqRef->labelsize(14);
          pltFreqRef->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
          pltFreqRef->align(FL_ALIGN_CENTER);
          pltFreqRef->when(FL_WHEN_RELEASE);
        } // XYplot* pltFreqRef
        { btnFreqRefCalibrate = new Fl_Button(418, 124, 75, 24, _("Calibrate"));
          btnFreqRefCalibrate->tooltip(_("Perform Freq Ref Calibration"));
          btnFreqRefCalibrate->callback((Fl_Callback*)cb_btnFreqRefCalibrate);
        } // Fl_Button* btnFreqRefCalibrate
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 45, 500, 255, _("Phase"));
        o->hide();
        { phase[0] = new Fl_Input(20, 54, 40, 24, _("1"));
        } // Fl_Input* phase[0]
        { phase[1] = new Fl_Input(81, 54, 40, 24, _("2"));
        } // Fl_Input* phase[1]
        { phase[2] = new Fl_Input(142, 54, 40, 24, _("3"));
        } // Fl_Input* phase[2]
        { phase[3] = new Fl_Input(204, 54, 40, 24, _("4"));
        } // Fl_Input* phase[3]
        { phase[4] = new Fl_Input(265, 54, 40, 24, _("5"));
        } // Fl_Input* phase[4]
        { phase[5] = new Fl_Input(327, 54, 40, 24, _("6"));
        } // Fl_Input* phase[5]
        { phase[06] = new Fl_Input(388, 54, 40, 24, _("7"));
        } // Fl_Input* phase[06]
        { phase[7] = new Fl_Input(450, 54, 40, 24, _("8"));
        } // Fl_Input* phase[7]
        { phase[8] = new Fl_Input(20, 83, 40, 23, _("9"));
        } // Fl_Input* phase[8]
        { phase[9] = new Fl_Input(81, 82, 40, 24, _("10"));
        } // Fl_Input* phase[9]
        { phase[10] = new Fl_Input(142, 82, 40, 24, _("11"));
        } // Fl_Input* phase[10]
        { phase[11] = new Fl_Input(204, 82, 40, 24, _("12"));
        } // Fl_Input* phase[11]
        { phase[12] = new Fl_Input(265, 82, 40, 24, _("13"));
        } // Fl_Input* phase[12]
        { phase[13] = new Fl_Input(327, 82, 40, 24, _("14"));
        } // Fl_Input* phase[13]
        { phase[14] = new Fl_Input(388, 82, 40, 24, _("15"));
        } // Fl_Input* phase[14]
        { phase[15] = new Fl_Input(450, 82, 40, 24, _("16"));
        } // Fl_Input* phase[15]
        { pltPhase = new XYplot(10, 136, 480, 154, _("Plot Goes Here"));
          pltPhase->box(FL_DOWN_BOX);
          pltPhase->color((Fl_Color)FL_BACKGROUND2_COLOR);
          pltPhase->selection_color((Fl_Color)FL_BACKGROUND2_COLOR);
          pltPhase->labeltype(FL_NORMAL_LABEL);
          pltPhase->labelfont(0);
          pltPhase->labelsize(14);
          pltPhase->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
          pltPhase->align(FL_ALIGN_CENTER);
          pltPhase->when(FL_WHEN_RELEASE);
        } // XYplot* pltPhase
        { btnReadPhaseData = new Fl_Button(75, 109, 75, 24, _("Read"));
          btnReadPhaseData->tooltip(_("Read NRAM values from rig."));
          btnReadPhaseData->callback((Fl_Callback*)cb_btnReadPhaseData);
        } // Fl_Button* btnReadPhaseData
        { btnSetPhaseData = new Fl_Button(220, 109, 75, 24, _("Write"));
          btnSetPhaseData->tooltip(_("Write values to rig NRAM"));
          btnSetPhaseData->callback((Fl_Callback*)cb_btnSetPhaseData);
        } // Fl_Button* btnSetPhaseData
        { btnPhaseCalibrate = new Fl_Button(365, 109, 75, 24, _("Calibrate"));
          btnPhaseCalibrate->tooltip(_("Perform Phase Calibration"));
          btnPhaseCalibrate->callback((Fl_Callback*)cb_btnPhaseCalibrate);
        } // Fl_Button* btnPhaseCalibrate
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 45, 500, 255, _("Carrier"));
        o->hide();
        { btnReadCarrierData = new Fl_Button(200, 65, 69, 24, _("Read"));
          btnReadCarrierData->tooltip(_("Read NRAM value from rig."));
          btnReadCarrierData->callback((Fl_Callback*)cb_btnReadCarrierData);
        } // Fl_Button* btnReadCarrierData
        { btnSetCarrierData = new Fl_Button(307, 65, 69, 24, _("Write"));
          btnSetCarrierData->tooltip(_("Write value to rig NRAM"));
          btnSetCarrierData->callback((Fl_Callback*)cb_btnSetCarrierData);
        } // Fl_Button* btnSetCarrierData
        { valCarrierBalance = new Fl_Input(120, 65, 60, 25, _("Carrier Balance:"));
          valCarrierBalance->type(2);
        } // Fl_Input* valCarrierBalance
        { btnCarrierBalance = new Fl_Button(415, 65, 69, 24, _("Balance"));
          btnCarrierBalance->tooltip(_("Perform Carrier Balance"));
          btnCarrierBalance->callback((Fl_Callback*)cb_btnCarrierBalance);
        } // Fl_Button* btnCarrierBalance
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 45, 500, 255, _("DVM"));
        o->hide();
        { txtAGC = new Fl_Output(105, 71, 60, 24, _("AGC:"));
          txtAGC->deactivate();
        } // Fl_Output* txtAGC
        { txtLockDet1 = new Fl_Output(105, 111, 60, 24, _("Lock Det 1:"));
          txtLockDet1->deactivate();
        } // Fl_Output* txtLockDet1
        { txtLockDet2 = new Fl_Output(105, 151, 60, 24, _("Lock Det 2:"));
          txtLockDet2->deactivate();
        } // Fl_Output* txtLockDet2
        { txtFwdPwr = new Fl_Output(105, 191, 60, 24, _("Fwd Pwr:"));
          txtFwdPwr->deactivate();
        } // Fl_Output* txtFwdPwr
        { txtRefPwr = new Fl_Output(105, 231, 60, 24, _("Ref Pwr:"));
          txtRefPwr->deactivate();
        } // Fl_Output* txtRefPwr
        { txtPhaseDet = new Fl_Output(310, 72, 60, 24, _("Phase Det:"));
          txtPhaseDet->deactivate();
        } // Fl_Output* txtPhaseDet
        { txtTxAudio = new Fl_Output(310, 111, 60, 24, _("Tx Audio:"));
          txtTxAudio->deactivate();
        } // Fl_Output* txtTxAudio
        { txtTempA = new Fl_Output(310, 151, 60, 24, _("Temp A:"));
          txtTempA->deactivate();
        } // Fl_Output* txtTempA
        { txtTempB = new Fl_Output(310, 191, 60, 24, _("Temp B:"));
          txtTempB->deactivate();
        } // Fl_Output* txtTempB
        { txtTCXO = new Fl_Output(310, 231, 60, 24, _("TCXO:"));
        } // Fl_Output* txtTCXO
        { btnReadAGC = new Fl_Button(175, 71, 49, 24, _("Read"));
          btnReadAGC->callback((Fl_Callback*)cb_btnReadAGC);
          btnReadAGC->hide();
        } // Fl_Button* btnReadAGC
        { btnReadLockDet1 = new Fl_Button(175, 111, 49, 24, _("Read"));
          btnReadLockDet1->callback((Fl_Callback*)cb_btnReadLockDet1);
          btnReadLockDet1->hide();
        } // Fl_Button* btnReadLockDet1
        { btnReadLockDet2 = new Fl_Button(175, 151, 49, 24, _("Read"));
          btnReadLockDet2->callback((Fl_Callback*)cb_btnReadLockDet2);
          btnReadLockDet2->hide();
        } // Fl_Button* btnReadLockDet2
        { btnReadFwdPwr = new Fl_Button(175, 191, 49, 24, _("Read"));
          btnReadFwdPwr->callback((Fl_Callback*)cb_btnReadFwdPwr);
          btnReadFwdPwr->hide();
        } // Fl_Button* btnReadFwdPwr
        { btnReadRefPwr = new Fl_Button(175, 231, 49, 24, _("Read"));
          btnReadRefPwr->callback((Fl_Callback*)cb_btnReadRefPwr);
          btnReadRefPwr->hide();
        } // Fl_Button* btnReadRefPwr
        { btnPhaseDet = new Fl_Button(380, 71, 49, 24, _("Read"));
          btnPhaseDet->callback((Fl_Callback*)cb_btnPhaseDet);
          btnPhaseDet->hide();
        } // Fl_Button* btnPhaseDet
        { btnTxAudio = new Fl_Button(380, 111, 49, 24, _("Read"));
          btnTxAudio->callback((Fl_Callback*)cb_btnTxAudio);
          btnTxAudio->hide();
        } // Fl_Button* btnTxAudio
        { btnReadTempA = new Fl_Button(380, 151, 49, 24, _("Read"));
          btnReadTempA->callback((Fl_Callback*)cb_btnReadTempA);
          btnReadTempA->hide();
        } // Fl_Button* btnReadTempA
        { btnReadTempB = new Fl_Button(380, 191, 49, 24, _("Read"));
          btnReadTempB->callback((Fl_Callback*)cb_btnReadTempB);
          btnReadTempB->hide();
        } // Fl_Button* btnReadTempB
        { btnReadTCXO = new Fl_Button(380, 231, 49, 24, _("Read"));
          btnReadTCXO->tooltip(_("Read NRAM value from rig."));
          btnReadTCXO->callback((Fl_Callback*)cb_btnReadTCXO);
        } // Fl_Button* btnReadTCXO
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Choice *selectCommPort=(Fl_Choice *)0;

Fl_Return_Button *btnOkCommsDialog=(Fl_Return_Button *)0;

static void cb_btnOkCommsDialog(Fl_Return_Button*, void*) {
  cbOkCommsDialog();
}

Fl_Double_Window* CommsDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(323, 104, _("Select"));
    w = o;
    o->box(FL_UP_BOX);
    { selectCommPort = new Fl_Choice(34, 60, 175, 21, _("Port:"));
      selectCommPort->down_box(FL_BORDER_BOX);
      selectCommPort->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Choice* selectCommPort
    { btnOkCommsDialog = new Fl_Return_Button(218, 60, 68, 21, _("OK"));
      btnOkCommsDialog->callback((Fl_Callback*)cb_btnOkCommsDialog);
    } // Fl_Return_Button* btnOkCommsDialog
    { new Fl_Box(5, 3, 312, 41, _("Select the KC505 serial port"));
    } // Fl_Box* o
    o->set_modal();
    o->end();
  } // Fl_Double_Window* o
  return w;
}
