// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef kctsdialog_h
#define kctsdialog_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "support.h"
#include <FL/Fl_Menu_Bar.H>
#include "debug.h"
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
extern Fl_Output *txtFirmware;
extern Fl_Output *txtHardware;
#include <FL/Fl_Input.H>
extern Fl_Input *txtSerialNumber;
#include <FL/Fl_Button.H>
extern Fl_Button *btnSendSerialNbr;
extern Fl_Output *txtRxSigLevel;
extern Fl_Output *txtTemperature;
extern Fl_Output *txtFwdPower;
extern Fl_Output *txtRefPower;
extern Fl_Button *btnReadAll;
extern Fl_Input *sMeter[16];
extern Fl_Button *btnReadSmeter;
extern Fl_Button *btnSetSmeterData;
extern Fl_Button *btnPerformSMeterCalibration;
#include "XYplot.h"
extern XYplot *pltSMeter;
extern Fl_Input *freqRef[32];
extern Fl_Button *btnReadFreqRefData;
extern Fl_Button *btnSetFreqRefData;
extern XYplot *pltFreqRef;
extern Fl_Button *btnFreqRefCalibrate;
extern Fl_Input *phase[16];
extern XYplot *pltPhase;
extern Fl_Button *btnReadPhaseData;
extern Fl_Button *btnSetPhaseData;
extern Fl_Button *btnPhaseCalibrate;
extern Fl_Button *btnReadCarrierData;
extern Fl_Button *btnSetCarrierData;
extern Fl_Input *valCarrierBalance;
extern Fl_Button *btnCarrierBalance;
extern Fl_Output *txtAGC;
extern Fl_Output *txtLockDet1;
extern Fl_Output *txtLockDet2;
extern Fl_Output *txtFwdPwr;
extern Fl_Output *txtRefPwr;
extern Fl_Output *txtPhaseDet;
extern Fl_Output *txtTxAudio;
extern Fl_Output *txtTempA;
extern Fl_Output *txtTempB;
extern Fl_Output *txtTCXO;
extern Fl_Button *btnReadAGC;
extern Fl_Button *btnReadLockDet1;
extern Fl_Button *btnReadLockDet2;
extern Fl_Button *btnReadFwdPwr;
extern Fl_Button *btnReadRefPwr;
extern Fl_Button *btnPhaseDet;
extern Fl_Button *btnTxAudio;
extern Fl_Button *btnReadTempA;
extern Fl_Button *btnReadTempB;
extern Fl_Button *btnReadTCXO;
extern Fl_Output *txtOpHours;
extern Fl_Button *btnReadOnTimeData;
extern Fl_Button *btnClearOnTimeData;
Fl_Double_Window* make_TSdialog();
extern Fl_Menu_Item menu_[];
#define mnuOpen (menu_+1)
#define mnuSave (menu_+2)
#define mnuSaveAs (menu_+3)
#define mnuExit (menu_+4)
#define mnuEvents (menu_+6)
#define mnuAbout (menu_+7)
#include <FL/Fl_Choice.H>
extern Fl_Choice *selectCommPort;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *btnOkCommsDialog;
#include <FL/Fl_Box.H>
Fl_Double_Window* CommsDialog();
#endif
